/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tiarjlsjgnieboibaojn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpYXJqbHNqZ25pZWJvaWJhb2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjYzMjMsImV4cCI6MjA3MzQwMjMyM30.kD_8sW6INy2wB4Y08-5C5NJ_-khnmjnsnOH0j_W6Rxs"